version: '3.9'

services:
  bot:
    build: ./bot
    container_name: shop-bot
    restart: always
    env_file:
      - ./bot/.env
    volumes:
      - ./bot:/app
    depends_on:
      - db

  web:
    build: ./web
    container_name: shop-web
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - ./web:/app
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: shop-db
    restart: always
    environment:
      POSTGRES_USER: shopuser
      POSTGRES_PASSWORD: shoppass
      POSTGRES_DB: shopdb
    volumes:
      - ./data/db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
